<?php
use MapasCulturais\i;

return array(
    1 => array(
       // 'slug' => i::__('tag'),
    'slug' => 'tag',
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        //'slug' => i::__('area'),
'slug' => 'area',
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__('Academia de Arte/Cultura'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Arte e Educação'),
            i::__('Artes Clássicas'),
            i::__('Artes do Espetáculo'),
            i::__('Artes Integradas'),
            i::__('Artes Manuais'),
            i::__('Artes Marciais - Aikido '),
            i::__('Artes Marciais - Boxe'),
            i::__('Artes Marciais - Boxe Chinês'),
            i::__('Artes Marciais -jiu-Jitsu'),
            i::__('Artes Marciais - Judô'),
            i::__('Artes Marciais - Karatê'),
            i::__('Artes Marciais - Kombato'),
            i::__('Artes Marciais - Krav Magá'),
            i::__('Artes Marciais - Kung Fu'),
            i::__('Artes Marciais - Luta Majoara'),
            i::__('Artes Marciais - MMA'),
            i::__('Artes Marciais - Muay Thai'),
            i::__('Artes Marciais - Shuai Jiao'),
            i::__('Artes Marciais - Taekwondo'),
            i::__('Artes Marciais - Tai Chi Chuan'),
            i::__('Artes Marciais - Tarracá'),
            i::__('Artes Marciais - Uru-Can'),
            i::__('Artes Marciais - Vale Tudo'),
            i::__('Outros - Artes Marciais'),
            i::__('Artes Visuais'),
            i::__('Artes e Ofícios - Guia Turístico'),
            i::__('Artesanato'),
            i::__('Audiovisual'),
            i::__('Cabeleireira'),
            i::__('Cabeleireiro'),
            i::__('Capoeira'),
            i::__('Carnaval'),
            i::__('Casa de Show_Casas Noturnas'),
            i::__('Cerimonial'),
            i::__('Cinema'),
            i::__('Circo'),
            i::__('Coletivos Culturais'),
            i::__('Contação de Histórias'),
            i::__('Congado'),
            i::__('Cooperativa'),
            i::__('Corte e Costura'),
            i::__('Dança Clássica'),
            i::__('Dança Contemporânea'),
            i::__('Dança Popular'),
            i::__('Dança Urbana'),
            i::__('Dança Tradicional Brasileira'),
            i::__('Dança Popular Tradicional'),
            i::__('Dança Acadêmica'),
            i::__('Dança Jazz'),
            i::__('Outros - Dança'),
            i::__('Desenho'),
            i::__('Design de Cílios'),
            i::__('Design de Interiores'),
            i::__('Design de Moda'),
            i::__('Design de Sobrancelhas'),
            i::__('Design de Unhas'),
            i::__('Design Gráfico'),
            i::__('Web Design'),
            i::__('Outros - Design'),
            i::__('Direito Autoral'),
            i::__('Economia Criativa'),
            i::__('Economia da Cultura'),
            i::__('Economia Solidária'),
            i::__('Outros - Economia'),
            i::__('Escola de Arte'),
            i::__('Escultura'),
            i::__('Estética da Mulher'),
            i::__('Expressões Artísticas Culturais Afro-Brasileiras'),
            i::__('Folia de Reis'),
            i::__('Fotografia'),
            i::__('Gastronomia - Bares'),
            i::__('Gastronomia - Cafeterias'),
            i::__('Gastronomia - Comida de Buteco'),
            i::__('Gastronomia - Comidas Exóticas'),
            i::__('Gastronomia - Comidas Tradicionais'),
            i::__('Gastronomia - Confeitarias'),
            i::__('Gastronomia - Docerias'),
            i::__('Gastronomia - Restaurantes'),
            i::__('Outros - Gastronomia'),
            i::__('Ginástica - Artística'),
            i::__('Ginástica - Rítmica'),
            i::__('Outros - Ginática'),
            i::__('Gravura'),
            i::__('Humor'),
            i::__('Igrejas, Religiões, Templos e Crenças - Assmbleia de Deus'),
            i::__('Igrejas, Religiões, Templos e Crenças - Bahaismo'),
            i::__('Igrejas, Religiões, Templos e Crenças - BudisBahaismo'),
            i::__('Igrejas, Religiões, Templos e Crenças - Candomblé'),
            i::__('Igrejas, Religiões, Templos e Crenças - Congregação Cristã do Brasil'),
            i::__('Igrejas, Religiões, Templos e Crenças - Crenças Indígenas'),
            i::__('Igrejas, Religiões, Templos e Crenças - Hare Krishna'),
            i::__('Igrejas, Religiões, Templos e Crenças - Hinduismo'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Adventista do Sétimo Dia'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Batista'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Católica Apostólica Romana'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Católica Ortodoxa'), 
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Deus é Amor'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja do Evangelho Quadrangular'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Luterana'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Messiânica'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Metodista'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Presbiteriana'),
            i::__('Igrejas, Religiões, Templos e Crenças - Igreja Universal do Reino de Deus'),
            i::__('Igrejas, Religiões, Templos e Crenças - Islamismo'),
            i::__('Igrejas, Religiões, Templos e Crenças - Judaísmo'),
            i::__('Igrejas, Religiões, Templos e Crenças - Kardecismo'),
            i::__('Igrejas, Religiões, Templos e Crenças - Mórmon'),
            i::__('Igrejas, Religiões, Templos e Crenças - Omolokó'),
            i::__('Igrejas, Religiões, Templos e Crenças - Outros Penteconstais e Neopentecostais'),
            i::__('Igrejas, Religiões, Templos e Crenças - Quimbanda'),
            i::__('Igrejas, Religiões, Templos e Crenças - Santo Daime'),
            i::__('Igrejas, Religiões, Templos e Crenças - Seicho-no-iê'),
            i::__('Igrejas, Religiões, Templos e Crenças - Taoismo'),
            i::__('Igrejas, Religiões, Templos e Crenças - Testemunhas de Jeová'),
            i::__('Igrejas, Religiões, Templos e Crenças - Tradições Esotéricas'),
            i::__('Igrejas, Religiões, Templos e Crenças - Umbanda'),
            i::__('Igrejas, Religiões, Templos e Crenças - Xintoismo'),
            i::__('Outros - Igrejas, Religiões, Templos e Crenças'),
            i::__('Ilustração'),
            i::__('Jogos Eletrônicos - Games'),
            i::__('Jornalismo'),
            i::__('Leitura'),
            i::__('Literatura'),
            i::__('Livro'),
            i::__('Mídias Livres'),
            i::__('Mídias Sociais'),
            i::__('Moda'),
            i::__('Museu'),
            i::__('Música - Banda Marcial'),
            i::__('Música - Canto Coral'),
            i::__('Música Cerimonial'),
            i::__('Música Eletrônica'),
            i::__('Música Erudita'),
            i::__('Música Gospel'),
            i::__('Música Litúrgica'),
            i::__('Música Popular'),
            i::__('Música Sacra'),
            i::__('Outros - Música'),
            i::__('Novas Mídias'),
            i::__('Pastourinhas'),
            i::__('Performance'),
            i::__('Pintura'),
            i::__('Ponto de Cultura'),
            i::__('Povos de Terreiros afro-brasileiros'),
            i::__('Produção e Gestão Cultural'),
            i::__('Quilombola'),
            i::__('Rádio'),
            i::__('Reisado'),
            i::__('Teatro de Bonecos'),
            i::__('Teatro de Fantoches'),
            i::__('Teatro de Palco'),
            i::__('Teatro de Rua'),
            i::__('Outros - Teatro'),
            i::__('Patrimônio Histórico e Cultural - Antropologia'),
            i::__('Patrimônio Histórico e Cultural - Arqueologia'),
            i::__('Patrimônio Histórico e Cultural - Arquitetura e Urbanismo'),
            i::__('Patrimônio Histórico e Cultural - Arquivos'),
            i::__('Patrimônio Histórico e Cultural - Associação Comunitária'),
            i::__('Patrimônio Histórico e Cultural - Associação Cultural'),
            i::__('Patrimônio Histórico e Cultural - Associação de Bairro'),
            i::__('Outros - Patrimônio Histórico e Cultural - Associações'),
            i::__('Patrimônio Histórico e Cultural - Biblioteca'),
            i::__('Patrimônio Histórico e Cultural - Centros Culturais'),
            i::__('Patrimônio Histórico e Cultural - Circuito de Presépios'),
            i::__('Patrimônio Histórico e Cultural - Coleções Particulares'),
            i::__('Patrimônio Histórico e Cultural - Comuinidade de Pescadores Artesanais'),
            i::__('Patrimônio Histórico e Cultural - Comunidade de Povos Ciganos'),
            i::__('Patrimônio Histórico e Cultural - Comunidade de Povos de Terreiro afro-brasieiros'),
            i::__('Patrimônio Histórico e Cultural - Comunidade Indígena'),
            i::__('Patrimônio Histórico e Cultural - Comunidade de Matriz Africana'),
            i::__('Patrimônio Histórico e Cultural - Cuminidades Extrativistas'),
            i::__('Patrimônio Histórico e Cultural - Comunidades Ribeirinhas'),
            i::__('Patrimônio Histórico e Cultural - Comunidades Rurais'),
            i::__('Patrimônio Histórico e Cultural - Quilombolas'),
            i::__('Outras - Comunidades - Patrimônio Histórico e Cultural'),
            i::__('Patrimônio Histórico e Cultural - Cultura Afro-Brasileira'),
            i::__('Patrimônio Histórico e Cultural - Cultura Cigana'),
            i::__('Patrimônio Histórico e Cultural - Cultura DEF'),
            i::__('Patrimônio Histórico e Cultural - Cultura Digital'),
            i::__('Patrimônio Histórico e Cultural - Cultura e Comunicação'),
            i::__('Patrimônio Histórico e Cultural - Cultura e Direitos Humanos'),
            i::__('Patrimônio Histórico e Cultural - Cultura e Educação'),
            i::__('Patrimônio Histórico e Cultural - Cultura e Esporte'),
            i::__('Patrimônio Histórico e Cultural - Cultura e Meio Ambiente'),
            i::__('Patrimônio Histórico e Cultural - Cultura e Saúde'),
            i::__('Patrimônio Histórico e Cultural - Cultural Hip-Hop e Funk'),
            i::__('Patrimônio Histórico e Cultural - Cultura LGBTQIAPN+'),
            i::__('Patrimônio Histórico e Cultural - Cultura Negra'),
            i::__('Patrimônio Histórico e Cultural - Cultura Popular'),
            i::__('Patrimônio Histórico e Cultural - Cultura, infância e Adolescência'),
            i::__('Patrimônio Histórico e Cultural - Culturas dos Povos de Comunidades Tradicionais de Matriz Africana'),
            i::__('Patrimônio Histórico e Cultural - Culturas dos Povos Indígenas'),
            i::__('Patrimônio Histórico e Cultural - Culturas dos Povos Nômades'),
            i::__('Patrimônio Histórico e Cultural - Culturas Estrangeiras'),
            i::__('Patrimônio Histórico e Cultural - Culturas Populares'),
            i::__('Patrimônio Histórico e Cultural - Culturas Quilombolas'),
            i::__('Patrimônio Histórico e Cultural - Culturas afro-brasileiras em suas diversas manifestações'),
            i::__('Outras - Cultura - Patrimônio Histórico e Cultural'),
            i::__('Patrimônio Histórico e Cultural - Eventos'),
            i::__('Patrimônio Histórico e Cultural - Festas Populares'),
            i::__('Patrimônio Histórico e Cultural - Festejos Juninos e Julhinos'),
            i::__('Patrimônio Histórico e Cultural - Festas Religiosas'),
            i::__('Patrimônio Histórico e Cultural - Festas Tradicionais'),
            i::__('Patrimônio Histórico e Cultural - Festas Regionais'),
            i::__('Outras - Festas - Patrimônio Histórico e Cultural'),
            i::__('Patrimônio Histórico e Cultural - Filosofia'),
            i::__('Patrimônio Histórico e Cultural - História e Cultura'),
            i::__('Patrimônio Histórico e Cultural - História Luzienses'),
            i::__('Patrimônio Histórico e Cultural - Intercâmbio Cultural'),
            i::__('Patrimônio Histórico e Cultural - Jornalismo'),
            i::__('Patrimônio Histórico e Cultural - Movimentos Sociais'),
            i::__('Patrimônio Histórico e Cultural - Museus'),
            i::__('Patrimônio Histórico e Cultural - Patrimônio Imaterial'),
            i::__('Patrimônio Histórico e Cultural - Patrimônio intangível'),
            i::__('Patrimônio Histórico e Cultural - Patrimônio material'),
            i::__('Patrimônio Histórico e Cultural - Patrimônio tangível'),
            i::__('Patrimônio Histórico e Cultural - Pesquisa em Cultura'),
            i::__('Patrimônio Histórico e Cultural - Salas de memória'),
            i::__('Patrimônio Histórico e Cultural - Tradições Populares'),
            i::__('Patrimônio Histórico e Cultural - Turismo Hoteis'),
            i::__('Patrimônio Histórico e Cultural - Pontos Turísticos'),
            i::__('Patrimônio Histórico e Cultural - Turismo Pousadas'),
            i::__('OUtros - Turismo -Patrimônio Histórico e Cultural')                   


        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Academia de Arte/Cultura'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Arte e Educação'),
            i::__('Artes Clássicas'),
            i::__('Artes do Espetáculo'),
            i::__('Artes Integradas'),
            i::__('Artes Manuais'),
            i::__('Artes Marciais - Aikido '),
            i::__('Artes Marciais - Boxe'),
            i::__('Artes Marciais - Boxe Chinês'),
            i::__('Artes Marciais -jiu-Jitsu'),
            i::__('Artes Marciais - Judô'),
            i::__('Artes Marciais - Karatê'),
            i::__('Artes Marciais - Kombato'),
            i::__('Artes Marciais - Krav Magá'),
            i::__('Artes Marciais - Kung Fu'),
            i::__('Artes Marciais - Luta Majoara'),
            i::__('Artes Marciais - MMA'),
            i::__('Artes Marciais - Muay Thai'),
            i::__('Artes Marciais - Shuai Jiao'),
            i::__('Artes Marciais - Taekwondo'),
            i::__('Artes Marciais - Tai Chi Chuan'),
            i::__('Artes Marciais - Tarracá'),
            i::__('Artes Marciais - Uru-Can'),
            i::__('Artes Marciais - Vale Tudo'),
            i::__('Artes Circenses'),
            i::__('Artes Integradas'),
            i::__('Artes Visuais'),
            i::__('Audiovisual'),
            i::__('Capoeira'),
            i::__('Carnaval'),
            i::__('Cinema'),
            i::__('Circo'),
            i::__('Coletivos Culturais'),
            i::__('Contação de Histórias'),
            i::__('Congado'),
            i::__('Cooperativa'),
            i::__('Corte e Costura'),
            i::__('Cultura Digital'),
            i::__('Cultura Indígena'),
            i::__('Cultura Tradicional'),
            i::__('Curso ou Oficina'),
            i::__('Dança'),
            i::__('Exposição'),
            i::__('Hip Hop'),
            i::__('Livro e Literatura'),
            i::__('Música Popular'),
            i::__('Música Erudita'),
            i::__('Palestra, Debate ou Encontro'),
            i::__('Rádio'),
            i::__('Teatro'),
            i::__('Outros')
        )
    )
);